workspace 'SDWebImageDemo.xcworkspace'

source 'git@e.coding.net:clife-devops/public-repository/ios-clifeSpecs.git'
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/mirrors/CocoaPods-Specs‘
#source 'https://git.coding.net/CocoaPods/Specs.git'


# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
        end
    end
end

target 'SDWebImageDemo' do
project 'SDWebImageDemo.xcodeproj'
    pod 'QMUIKit'
    pod 'SDWebImage', '~> 5.8.4'
    pod 'Masonry', '~> 1.1.0'
end

